# Generated by Django 3.2.8 on 2021-11-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('short_description', models.CharField(max_length=45, verbose_name='short_description')),
                ('long_description', models.CharField(max_length=300, verbose_name='long_description')),
                ('color', models.CharField(max_length=25, verbose_name='color')),
                ('img_url', models.CharField(max_length=300, verbose_name='img_url')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle_app.vehicle_type')),
            ],
        ),
    ]
