# Generated by Django 3.2.9 on 2021-11-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_type',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='name'),
        ),
    ]
