# Generated by Django 3.2.8 on 2021-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0003_alter_vehicle_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
