# Generated by Django 3.2.8 on 2021-11-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0004_auto_20211124_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='vehicle_app.vehicle_type'),
        ),
    ]
